version: '3.9'
services:
  dockerc:
    build: dockerc
    image: ireshmm/dockerc
    command: sleep infinity
    volumes:
      - ../:/workspace:cached
      - jenkins-data:/jenkins-data
      - /home/iresh/.ssh/id_rsa:/home/vscode/.ssh/id_rsa
      - /home/iresh/.ssh/id_rsa.pub:/home/vscode/.ssh/id_rsa.pub
    networks:
      - ci-network

volumes:
  jenkins-data:
    name: jenkins-data
    external: true
networks:
  ci-network:
    name: ci-network
    external: true