version: '3.9'
services:
  dockerc:
    build: dockerc
    image: ireshmm/dockerc
    command: sleep infinity
    volumes:
      - ../:/workspace:cached
      - jenkins-data:/jenkins-data
      - /home/iresh/.ssh:/home/vscode/.ssh

volumes:
  jenkins-data:
    name: nable-ci-stack_jenkins-data
    external: true